* inst/examples/sge-cluster/: Modernize.
git-svn-id: file:///home/manu/work/irace/svn/trunk@850 d10a546b-4b69-48e5-8b66-49ccea70c6a4

diff --git a/inst/examples/sge-cluster/hook-run b/inst/examples/sge-cluster/hook-run
--- a/inst/examples/sge-cluster/hook-run
+++ b/inst/examples/sge-cluster/hook-run
@@ -27,9 +27,6 @@ CAND_PARAMS=$*
 STDOUT=c${CANDIDATE}.stdout
 STDERR=c${CANDIDATE}.stderr
 
-mkdir -p arena
-cd arena
-
 # We use 'exec' to avoid creating another process. There can be no
 # other commands after exec.
 exec qsub <<EOF
@@ -49,5 +46,21 @@ RET=\$?
 echo "OK" >& 2
 mv \$TMP/* ./
 rmdir -p \$TMP &> /dev/null
-exit \$RET
+
+error() {
+    echo "`TZ=UTC date`: error: \$@"
+    exit 1
+}
+
+# This is an example of reading a number from the output. It assumes
+# that the objective value is the first number in the first column of
+# the only line starting with a digit.
+if [ -s "\${STDOUT}" ]; then
+    COST=\$(cat \${STDOUT} | grep -e '^[0-9]' | cut -f1)
+    echo "\$COST"
+    rm -f "\${STDOUT}" "\${STDERR}"
+    exit 0
+else
+    error "\${STDOUT}: No such file or directory"
+fi
 EOF
