* inst/examples/hypervolume/target-evaluator: Fix bash code.  * inst/examples/sge-cluster/target-evaluator: Update to only delete non-elite files.  * inst/examples/sge-cluster/target-runner: Output files have also instance id.
git-svn-id: file:///home/manu/work/irace/svn/trunk@1714 d10a546b-4b69-48e5-8b66-49ccea70c6a4

diff --git a/inst/examples/sge-cluster/target-runner b/inst/examples/sge-cluster/target-runner
--- a/inst/examples/sge-cluster/target-runner
+++ b/inst/examples/sge-cluster/target-runner
@@ -26,18 +26,22 @@ CANDIDATE=$1
 INSTANCEID=$2
 SEED=$3
 INSTANCE=$4
-shift 4 || exit 1
+shift 4 || error "Not enough parameters to $0"
 CAND_PARAMS=$*
 
+STDOUT=c${CANDIDATE}-${INSTANCEID}.stdout
+STDERR=c${CANDIDATE}-${INSTANCEID}.stderr
 
-STDOUT=c${CANDIDATE}.stdout
-STDERR=c${CANDIDATE}.stderr
+error() {
+    echo "`TZ=UTC date`: error: $@"
+    exit 1
+}
 
 # We use 'exec' to avoid creating another process. There can be no
 # other commands after exec.
 exec qsub <<EOF
 #!/bin/bash
-#$ -N irace-$PPID-$CANDIDATE
+#$ -N irace-$PPID-$CANDIDATE-${INSTANCEID}
 #$ -l xeon5410
 # -l long
 #$ -m as
