* The option --sge-cluster (sgeCluster) was removed and replaced by    --batchmode (batchmode). It is now the responsibility of the target-runner to    parse the output of the batch job submission command (e.g., qsub or squeue),    and return just the job ID. Values supported are: "sge", "torque", "pbs" and    "slurm".                                                      (Manuel López-Ibáñez)
 * The option --parallel can now be combined with --batchmode to limit the
   number of jobs submitted by irace at once. This may be useful in batch
   clusters that have a small queue of jobs.
                                                   (Manuel López-Ibáñez)

 * New examples under inst/examples/batchmode-cluster/.
                                                       (Manuel López-Ibáñez)

 * It is now possible to include scenario definition files from other scenario
   files by using:
   
      eval.parent(source("scenario-common.txt", chdir = TRUE, local = TRUE))

   This feature is VERY experimental and the syntax is likely to change in the
   future.                                             (Manuel López-Ibáñez)
 


git-svn-id: file:///home/manu/work/irace/svn/trunk@1732 d10a546b-4b69-48e5-8b66-49ccea70c6a4

diff --git a/inst/examples/sge-cluster/target-runner-sge b/inst/examples/sge-cluster/target-runner-sge
--- a/inst/examples/sge-cluster/target-runner-sge
+++ b/inst/examples/sge-cluster/target-runner-sge
@@ -19,6 +19,8 @@
 # This script should print nothing.
 # Exit with 0 if no error, with 1 in case of error
 ###############################################################################
+tmpfile=$(mktemp)
+
 EXE=~/bin/program
 FIXED_PARAMS=""
 
@@ -34,12 +36,12 @@ STDERR=c${CANDIDATE}-${INSTANCEID}.stderr
 
 error() {
     echo "`TZ=UTC date`: error: $@"
+    cat $tmpfile
+    rm -f $tmpfile
     exit 1
 }
 
-# We use 'exec' to avoid creating another process. There can be no
-# other commands after exec.
-exec qsub <<EOF
+qsub &> $tmpfile <<EOF
 #!/bin/bash
 #$ -N irace-$PPID-$CANDIDATE-${INSTANCEID}
 #$ -l xeon5410
@@ -58,3 +60,16 @@ mv \$TMP/* ./
 rmdir -p \$TMP &> /dev/null
 exit \$RET
 EOF
+
+rc=$?
+if [[ $rc == 0 ]]; then
+    JOBID=$(grep -o -e "Your job [^ ]\+" $tmpfile | cut -f3 -d ' ')
+    if ! [[ "$JOBID" =~ ^[_-.@0-9A-Za-z]+$ ]] ; then
+        error "$0: cannot parse jobID from the output of qsub!"
+    fi
+    echo "$JOBID"
+    rm -f $tmpfile
+    exit 0
+else
+    error "$0: qsub failed!"
+fi
