In all target-runner, target-evaluator examples using Bash, define functions at the top of the file. It seems some versions of Bash require this.
https://groups.google.com/forum/#!msg/irace-package/BwNAtcK-MRs/Q_8w-_B3AgAJ



git-svn-id: file:///home/manu/work/irace/svn/trunk@1924 d10a546b-4b69-48e5-8b66-49ccea70c6a4

diff --git a/inst/examples/acotsp/target-runner b/inst/examples/acotsp/target-runner
--- a/inst/examples/acotsp/target-runner
+++ b/inst/examples/acotsp/target-runner
@@ -12,6 +12,11 @@
 # RETURN VALUE:
 # This script should print a single numerical value (the value to be minimized).
 ###############################################################################
+error() {
+    echo "`TZ=UTC date`: $0: error: $@" >&2
+    exit 1
+}
+
 
 # Path to the ACOTSP software:
 EXE=~/bin/acotsp
@@ -25,17 +30,11 @@ INSTANCE_ID="$2"
 SEED="$3"
 INSTANCE="$4"
 # All other parameters are the candidate parameters to be passed to program
-shift 4 || error "Not enough parameters to $0"
+shift 4 || error "Not enough parameters"
 CONFIG_PARAMS=$*
 
 STDOUT=c${CONFIG_ID}-${INSTANCE_ID}.stdout
 STDERR=c${CONFIG_ID}-${INSTANCE_ID}.stderr
-
-# In case of error, we print the current time:
-error() {
-    echo "`TZ=UTC date`: error: $@" >&2
-    exit 1
-}
 
 if [ ! -x "${EXE}" ]; then
     error "${EXE}: not found or not executable (pwd: $(pwd))"
diff --git a/inst/examples/batchmode-cluster/target-evaluator b/inst/examples/batchmode-cluster/target-evaluator
--- a/inst/examples/batchmode-cluster/target-evaluator
+++ b/inst/examples/batchmode-cluster/target-evaluator
@@ -20,21 +20,21 @@
 # This script should print one numerical value: the cost that must be minimized.
 # Exit with 0 if no error, with 1 in case of error
 ###############################################################################
+error() {
+    echo "`TZ=UTC date`: $0: error: $@"
+    exit 1
+}
+
 CANDIDATE="$1"
 INSTANCEID="$2"
 SEED="$3"
 INSTANCE="$4"
 TOTALCANDIDATES="$5"
-shift 5 || error "Not enough parameters to $0"
+shift 5 || error "Not enough parameters"
 ALLIDS=$*
 
 STDOUT=c${CANDIDATE}-${INSTANCEID}.stdout
 STDERR=c${CANDIDATE}-${INSTANCEID}.stderr
-
-error() {
-    echo "`TZ=UTC date`: error: $@"
-    exit 1
-}
 
 ALLFILES=
 for FILENAME in $ALLIDS; do
diff --git a/inst/examples/batchmode-cluster/target-runner-pbs b/inst/examples/batchmode-cluster/target-runner-pbs
--- a/inst/examples/batchmode-cluster/target-runner-pbs
+++ b/inst/examples/batchmode-cluster/target-runner-pbs
@@ -19,6 +19,11 @@
 # This script should print nothing.
 # Exit with 0 if no error, with 1 in case of error
 ###############################################################################
+error() {
+    echo "`TZ=UTC date`: $0: error: $@"
+    exit 1
+}
+
 EXE=~/bin/program
 FIXED_PARAMS=""
 
@@ -26,17 +31,11 @@ CANDIDATE=$1
 INSTANCEID=$2
 SEED=$3
 INSTANCE=$4
-shift 4 || error "Not enough parameters to $0"
+shift 4 || error "Not enough parameters"
 CAND_PARAMS=$*
 
 STDOUT=c${CANDIDATE}-${INSTANCEID}.stdout
 STDERR=c${CANDIDATE}-${INSTANCEID}.stderr
-
-error() {
-    echo "`TZ=UTC date`: error: $@"
-    exit 1
-}
-
 
 # PBS just prints the jobID, so it should be good to go.
 exec qsub <<EOF
diff --git a/inst/examples/batchmode-cluster/target-runner-slurm b/inst/examples/batchmode-cluster/target-runner-slurm
--- a/inst/examples/batchmode-cluster/target-runner-slurm
+++ b/inst/examples/batchmode-cluster/target-runner-slurm
@@ -19,6 +19,13 @@
 # This script should print nothing.
 # Exit with 0 if no error, with 1 in case of error
 ###############################################################################
+error() {
+    echo "`TZ=UTC date`: $0: error: $@"
+    cat $tmpfile
+    rm -f $tmpfile
+    exit 1
+}
+
 tmpfile=$(mktemp)
 
 EXE=~/bin/program
@@ -28,18 +35,11 @@ CANDIDATE=$1
 INSTANCEID=$2
 SEED=$3
 INSTANCE=$4
-shift 4 || error "Not enough parameters to $0"
+shift 4 || error "Not enough parameters"
 CAND_PARAMS=$*
 
 STDOUT=c${CANDIDATE}-${INSTANCEID}.stdout
 STDERR=c${CANDIDATE}-${INSTANCEID}.stderr
-
-error() {
-    echo "`TZ=UTC date`: error: $@"
-    cat $tmpfile
-    rm -f $tmpfile
-    exit 1
-}
 
 # modify with the SLURM submission template
 sbatch 1> $tmpfile <<EOF
diff --git a/inst/examples/hypervolume/target-evaluator b/inst/examples/hypervolume/target-evaluator
--- a/inst/examples/hypervolume/target-evaluator
+++ b/inst/examples/hypervolume/target-evaluator
@@ -20,6 +20,19 @@
 # RETURN VALUE:
 # This script should print a single numerical value
 ###############################################################################
+error() {
+    echo "`TZ=UTC date`: $0: error: $@"
+    if [ -s error.log ]; then
+        cat error.log
+    fi
+    exit 1
+}
+
+error_sleep() {
+    echo "`TZ=UTC date`: $0: error: $@" >> error.log
+    sleep 60
+}
+
 NORMALIZATION_RANGE="'1 2'"
 REFERENCE_POINT="'1.1 1.1'"
 
@@ -89,18 +102,4 @@ fi
 COST=$(eval "$HV ${STDOUT}_nor" || error "calculating hypervolume failed")
 # Negative because hypervolume is maximised but irace minimises.
 echo "-$COST"
-
-error() {
-    echo "`TZ=UTC date`: error: $@"
-    if [ -s error.log ]; then
-        cat error.log
-    fi
-    exit 1
-}
-
-error_sleep() {
-    echo "`TZ=UTC date`: error: $@" >> error.log
-    sleep 60
-}
-
 exit 0
diff --git a/inst/examples/hypervolume/target-runner b/inst/examples/hypervolume/target-runner
--- a/inst/examples/hypervolume/target-runner
+++ b/inst/examples/hypervolume/target-runner
@@ -14,6 +14,10 @@
 # This script should print nothing.
 # Exit with 0 if no error, with 1 in case of error
 ###############################################################################
+error() {
+    echo "`TZ=UTC date`: $0: oerror: $@"
+    exit 1
+}
 
 # NOTE: You need to customize EXE and FIXED_PARAMS below.  If you change the
 # rest, you need to also update target-evaluator
@@ -28,7 +32,7 @@ INSTANCEID="$2"
 SEED="$3"
 INSTANCE="$4"
 # All other parameters are the candidate parameters to be passed to program
-shift 4 || error "Not enough parameters to $0"
+shift 4 || error "Not enough parameters"
 CAND_PARAMS=$*
 
 STDOUT=c${CANDIDATE}-${INSTANCEID}.stdout
@@ -42,8 +46,3 @@ $EXE ${FIXED_PARAMS} ${CAND_PARAMS} 1> $STDOUT 2> $STDERR
 # We do this to make sure this target-runner terminated correctly in target-evaluator
 echo "OK" >> $STDERR
 exit 0
-
-error() {
-    echo "`TZ=UTC date`: error: $@"
-    exit 1
-}
diff --git a/inst/examples/matlab/target-runner b/inst/examples/matlab/target-runner
--- a/inst/examples/matlab/target-runner
+++ b/inst/examples/matlab/target-runner
@@ -17,6 +17,11 @@
 # This script should print one numerical value: the cost that must be minimized.
 # Exit with 0 if no error, with 1 in case of error
 ###############################################################################
+error() {
+    echo "`TZ=UTC date`: $0: error: $@"
+    exit 1
+}
+
 EXE=matlab
 FIXED_PARAMS="-nosplash -nodesktop -nodisplay"
 
@@ -24,7 +29,7 @@ CANDIDATE=$1
 INSTANCEID=$2
 SEED=$3
 INSTANCE=$4
-shift 4 || exit 1
+shift 4 ||  error "Not enough parameters"
 CAND_PARAMS=$*
 
 STDOUT=c${CANDIDATE}-${INSTANCEID}.stdout
@@ -40,11 +45,6 @@ STDERR=c${CANDIDATE}-${INSTANCEID}.stderr
 ## the command.)
 ## This example assumes that CAND_PARAMS contains something like "A=10 B=5"
 $EXE ${FIXED_PARAMS} -r "INSTANCE=${INSTANCEID};${CAND_PARAMS// /;};RUN(INSTANCE,A,B);exit" < RUN.m 1> ${STDOUT} 2> ${STDERR}
-
-error() {
-    echo "`TZ=UTC date`: error: $@"
-    exit 1
-}
 
 ## This may be used to introduce a delay if there are filesystem
 ## issues.
diff --git a/inst/examples/moaco/target-runner b/inst/examples/moaco/target-runner
--- a/inst/examples/moaco/target-runner
+++ b/inst/examples/moaco/target-runner
@@ -12,6 +12,11 @@
 # This script should print nothing.
 # Exit with 0 if no error, with 1 in case of error
 ###############################################################################
+error() {
+    echo "`TZ=UTC date`: $0: error: $@"
+    exit 1
+}
+
 # If you want to find where target-runner is.
 #BINDIR=$(dirname "$(readlink -f "$(type -P $0 || echo $0)")")
 EXE=~/bin/moaco_btsp
@@ -20,7 +25,7 @@ CONFIGURATION=$1
 INSTANCEID=$2
 SEED=$3
 INSTANCE=$4
-shift 4 || error "Not enough parameters to $0"
+shift 4 || error "Not enough parameters"
 
 STDOUT=c${CONFIGURATION}-${INSTANCEID}.stdout
 STDERR=c${CONFIGURATION}-${INSTANCEID}.stderr
@@ -55,7 +60,3 @@ RET=$?
 echo "OK" >& 2
 exit $RET
 
-error() {
-    echo "`TZ=UTC date`: error: $@"
-    exit 1
-}
diff --git a/inst/templates/target-runner.tmpl b/inst/templates/target-runner.tmpl
--- a/inst/templates/target-runner.tmpl
+++ b/inst/templates/target-runner.tmpl
@@ -16,6 +16,11 @@
 # This script should print one numerical value: the cost that must be minimized.
 # Exit with 0 if no error, with 1 in case of error
 ###############################################################################
+error() {
+    echo "`TZ=UTC date`: $0: error: $@"
+    exit 1
+}
+
 EXE=~/bin/program
 FIXED_PARAMS=""
 
@@ -23,7 +28,7 @@ CONFIG_ID=$1
 INSTANCE_ID=$2
 SEED=$3
 INSTANCE=$4
-shift 4 || exit 1
+shift 4 || error "Not enough parameters"
 CONFIG_PARAMS=$*
 
 STDOUT=c${CONFIG_ID}-${INSTANCE_ID}.stdout
@@ -42,11 +47,6 @@ fi
 # (If you wish to ignore segmentation faults you can use '{}' around
 # the command.)
 $EXE ${FIXED_PARAMS} -i $INSTANCE --seed ${SEED} ${CONFIG_PARAMS} 1> ${STDOUT} 2> ${STDERR}
-
-error() {
-    echo "`TZ=UTC date`: error: $@"
-    exit 1
-}
 
 # # This may be used to introduce a delay if there are filesystem
 # # issues.
