* examples/moaco: minor improvements to hooks.
git-svn-id: file:///home/manu/work/irace/svn/trunk@1471 d10a546b-4b69-48e5-8b66-49ccea70c6a4

diff --git a/inst/examples/moaco/target-evaluator b/inst/examples/moaco/target-evaluator
--- a/inst/examples/moaco/target-evaluator
+++ b/inst/examples/moaco/target-evaluator
@@ -61,7 +61,7 @@ calc_measure() {
     LIMITSTMP=limits-${INSTANCEID}.tmp
     if [ -s "$LIMITSFILE" ]; then
         eval "$NORMALIZE $LIMITSFILE $ALLFILES $UPDATELIMITS" > $LIMITSTMP
-        rm -f ${LIMITSFILE}_nor
+        rm -f ${LIMITSFILE}
         mv $LIMITSTMP $LIMITSFILE
     else
        eval "$NORMALIZE $ALLFILES $UPDATELIMITS" > $LIMITSFILE
@@ -69,9 +69,8 @@ calc_measure() {
 
 }
 
-target_runner_tmp="./target-runner-tmp"
-
-cd ${target_tunner_tmp} || error "cannot change to directory \'${target_tunner_tmp}\'"
+tmp="./target-runner-tmp"
+cd ${tmp} || error "cannot change to directory \'${tmp}\'"
 
 ALLFILES=
 for FILENAME in $ALLIDS; do
@@ -84,7 +83,7 @@ while ! ls ${ALLFILES}_nor &> /dev/null ; do
     # Check that all output files are there
     NUM=$(ls -1 ${ALLFILES} 2> /dev/null | wc --lines)
     if [ "$NUM" -ne "$TOTALCONFIGURATIONS" ]; then
-        error_sleep "only found $NUM files out of $TOTALCONFIGURATIONS"
+        error_sleep "only found $NUM files out of $TOTALCONFIGURATIONS: ${ALLFILES}"
         continue
     fi
     # Check every STDERR
diff --git a/inst/examples/moaco/target-runner b/inst/examples/moaco/target-runner
--- a/inst/examples/moaco/target-runner
+++ b/inst/examples/moaco/target-runner
@@ -2,7 +2,7 @@
 ###############################################################################
 #
 # PARAMETERS:
-# $1 is the candidate number
+# $1 is the configuration number
 # $2 is the instance id
 # $3 is the seed
 # $4 is the instance name
@@ -16,28 +16,29 @@
 EXE=~/bin/moaco_btsp
 RUNTIME="60"
 
-CANDIDATE=$1
+CONFIGURATION=$1
 INSTANCEID=$2
 SEED=$3
 INSTANCE=$4
 shift 4 || error "Not enough parameters to $0"
 
-STDOUT=c${CANDIDATE}-${INSTANCEID}.stdout
-STDERR=c${CANDIDATE}-${INSTANCEID}.stderr
+STDOUT=c${CONFIGURATION}-${INSTANCEID}.stdout
+STDERR=c${CONFIGURATION}-${INSTANCEID}.stderr
 
 # TODO: Use /tmp for all temporary files, i.e., put target-runner-data under /tmp
-mkdir -p target-runner-data
-cd target-runner-data
+tmp="./target-runner-tmp"
+mkdir -p ${tmp}
+cd ${tmp} || error "cannot change to directory \'${tmp}\'"
 
 # Here we transform some parameters.
 PARAMS=
-while [ $# -gt 0 ]
-do
-  case "$1" in
-      --Mants) shift; MANTS="$1"; let "ANTS = (10  * 3 * 2 * $MANTS)"; shift;;
-      --Isize) shift; ISIZE="$1"; let "RUNTIME = (4 * (($ISIZE / 100) ** 2))"; shift;;
-      *) PARAMS="$PARAMS $1"; shift;;# terminate case
-  esac
+while [ $# -gt 0 ]; do
+    case "$1" in
+        --ants) shift; ANTS="$1"; shift;;
+        --Mants) shift; MANTS="$1"; let "ANTS = (10  * 3 * 2 * $MANTS)"; shift;;
+        --Isize) shift; ISIZE="$1"; let "RUNTIME = (4 * (($ISIZE / 100) ** 2))"; shift;;
+        *) PARAMS="$PARAMS $1"; shift;;# terminate case
+    esac
 done
 
 FIXED_PARAMS="--trials 1 --time $RUNTIME --ants $ANTS --input $INSTANCE --seed $SEED"
