* examples/moaco: make hooks more similar to the ones actually run.
git-svn-id: file:///home/manu/work/irace/svn/trunk@1470 d10a546b-4b69-48e5-8b66-49ccea70c6a4

diff --git a/inst/examples/moaco/target-evaluator b/inst/examples/moaco/target-evaluator
--- a/inst/examples/moaco/target-evaluator
+++ b/inst/examples/moaco/target-evaluator
@@ -1,20 +1,21 @@
 #!/bin/bash
 ###############################################################################
-# This script is run for each candidate to evaluate it after all
+# This script is run for each configuration to evaluate it after all
 # candidate configurations have been run on a single instance.
 #
 # Check the examples in examples/
 #
 # PARAMETERS:
-# $1 is the candidate number
+# $1 is the configuration number
 # $2 is the instance id
 # $3 is the seed
 # $4 is the instance name
-# $5 is the number of candidates alive in this iteration
+# $5 is the total number of configurations alive in this iteration
+# The rest are the IDs of all configurations run for this instance
 #
-# ONLY FOR ELITIST RACE: The rest ($* after `shift 5') are the ids of the 
-# candidates alive in this iteration. This list can be used to calculate the 
-# hypervolume using previous execution results.
+# ONLY FOR ELITIST RACE: The rest ($* after `shift 5') are the ids of the
+# configurations alive in this iteration. This list can be used to calculate
+# the hypervolume using previous execution results.
 #
 # RETURN VALUE:
 # This script should print a single numerical value
@@ -24,22 +25,23 @@ REFERENCE_POINT="'2.1 2.1'"
 
 # A program that normalizes all _dat files to [0, 1]
 # (optional, not included).
-NORMALIZE="~/bin/normalize --verbose -n $NORMALIZATION_RANGE -s '_nor'"
+NORMALIZE="~/bin/nondominated --verbose -n $NORMALIZATION_RANGE -s '_nor'"
 UPDATELIMITS="2>&1 | grep -E '# Total minimum|# Total maximum'  | sed  's/:/:\n/'"
+
 # A program for computing the hypervolume. Download hypervolume
-# code from http://iridia.ulb.ac.be/~manuel/hypervolume
+# code from http://lopez-ibanez.eu/hypervolume
 HV="~/bin/hv --quiet -r $REFERENCE_POINT"
 
-CANDIDATE="$1"
+CONFIGURATION="$1"
 INSTANCEID="$2"
 SEED="$3"
 INSTANCE="$4"
-TOTALCANDIDATES="$5"
+TOTALCONFIGURATIONS="$5"
 shift 5 || error "Not enough parameters to $0"
 ALLIDS=$*
 
-STDOUT=c${CANDIDATE}-${INSTANCEID}.stdout
-STDERR=c${CANDIDATE}-${INSTANCEID}.stderr
+STDOUT=c${CONFIGURATION}-${INSTANCEID}.stdout
+STDERR=c${CONFIGURATION}-${INSTANCEID}.stderr
 
 error() {
     echo "`TZ=UTC date`: error: $@"
@@ -59,7 +61,7 @@ calc_measure() {
     LIMITSTMP=limits-${INSTANCEID}.tmp
     if [ -s "$LIMITSFILE" ]; then
         eval "$NORMALIZE $LIMITSFILE $ALLFILES $UPDATELIMITS" > $LIMITSTMP
-rm -f ${LIMITSFILE}_nor
+        rm -f ${LIMITSFILE}_nor
         mv $LIMITSTMP $LIMITSFILE
     else
        eval "$NORMALIZE $ALLFILES $UPDATELIMITS" > $LIMITSFILE
@@ -67,8 +69,9 @@ rm -f ${LIMITSFILE}_nor
 
 }
 
+target_runner_tmp="./target-runner-tmp"
 
-cd arena || error "cannot change to directory 'arena'"
+cd ${target_tunner_tmp} || error "cannot change to directory \'${target_tunner_tmp}\'"
 
 ALLFILES=
 for FILENAME in $ALLIDS; do
@@ -80,8 +83,8 @@ done
 while ! ls ${ALLFILES}_nor &> /dev/null ; do
     # Check that all output files are there
     NUM=$(ls -1 ${ALLFILES} 2> /dev/null | wc --lines)
-    if [ "$NUM" -ne "$TOTALCANDIDATES" ]; then
-        error_sleep "only found $NUM files out of $TOTALCANDIDATES"
+    if [ "$NUM" -ne "$TOTALCONFIGURATIONS" ]; then
+        error_sleep "only found $NUM files out of $TOTALCONFIGURATIONS"
         continue
     fi
     # Check every STDERR
@@ -94,14 +97,14 @@ while ! ls ${ALLFILES}_nor &> /dev/null ; do
     rm -f error.log
     # Comment out if you wish to keep all output files around
     comm --output-delimiter=" " -23 <(ls -1 c*-*.* | sort) <(ls -1 ${ALLFILES//-${INSTANCEID}.stdout/-*.*} | sort) | xargs -r rm -f
-    
+    break
 done
 
-if [ -s "${STDOUT}_nor" ]; then
-    COST=$( eval "$HV ${STDOUT}_nor" || error "calculating hypervolume failed")
-    # Negative because hypervolume is maximised but irace minimises.
-    echo "-$COST"
-    exit 0
-else
+if [ ! -s "${STDOUT}_nor" ]; then
     error "${STDOUT}_nor: No such file or directory"
 fi
+COST=$(eval "$HV ${STDOUT}_nor" || error "calculating hypervolume failed")
+# Negative because hypervolume is maximised but irace minimises.
+echo "-$COST"
+exit 0
+
diff --git a/inst/examples/moaco/target-runner b/inst/examples/moaco/target-runner
--- a/inst/examples/moaco/target-runner
+++ b/inst/examples/moaco/target-runner
@@ -11,36 +11,44 @@
 # RETURN VALUE:
 # This script should print a single numerical value (the value to be minimized)
 ###############################################################################
+# If you want to find where target-runner is.
+#BINDIR=$(dirname "$(readlink -f "$(type -P $0 || echo $0)")")
 EXE=~/bin/moaco_btsp
-
-FIXED_PARAMS=" --trials 1 --wls 0 --aco mmas --time 60 "
+RUNTIME="60"
 
 CANDIDATE=$1
 INSTANCEID=$2
 SEED=$3
 INSTANCE=$4
-shift 4 || exit 1
-CAND_PARAMS=$*
+shift 4 || error "Not enough parameters to $0"
 
 STDOUT=c${CANDIDATE}-${INSTANCEID}.stdout
 STDERR=c${CANDIDATE}-${INSTANCEID}.stderr
 
-mkdir -p arena
-cd arena
+# TODO: Use /tmp for all temporary files, i.e., put target-runner-data under /tmp
+mkdir -p target-runner-data
+cd target-runner-data
 
 # Here we transform some parameters.
 PARAMS=
 while [ $# -gt 0 ]
 do
   case "$1" in
-      --Mants) shift; MANTS="$1"; shift;;
+      --Mants) shift; MANTS="$1"; let "ANTS = (10  * 3 * 2 * $MANTS)"; shift;;
+      --Isize) shift; ISIZE="$1"; let "RUNTIME = (4 * (($ISIZE / 100) ** 2))"; shift;;
       *) PARAMS="$PARAMS $1"; shift;;# terminate case
   esac
 done
-let "ANTS = (10  * 3 * 2 * $MANTS)"
+
+FIXED_PARAMS="--trials 1 --time $RUNTIME --ants $ANTS --input $INSTANCE --seed $SEED"
 
 exec 2> $STDERR
-$EXE ${FIXED_PARAMS} --input $INSTANCE --seed $SEED $PARAMS --ants $ANTS 1> $STDOUT
+$EXE ${FIXED_PARAMS} ${PARAMS} 1> $STDOUT
 RET=$?
 echo "OK" >& 2
 exit $RET
+
+error() {
+    echo "`TZ=UTC date`: error: $@"
+    exit 1
+}
