inst/examples/hypervolume, inst/examples/moaco: Modernize.
git-svn-id: file:///home/manu/work/irace/svn/trunk@1915 d10a546b-4b69-48e5-8b66-49ccea70c6a4

diff --git a/inst/examples/hypervolume/target-evaluator b/inst/examples/hypervolume/target-evaluator
--- a/inst/examples/hypervolume/target-evaluator
+++ b/inst/examples/hypervolume/target-evaluator
@@ -1,17 +1,21 @@
 #!/bin/bash
 ###############################################################################
-# This script is run for each candidate to evaluate it after all
+# This script is run for each configuration to evaluate it after all
 # candidate configurations have been run on a single instance.
 #
 # Check the examples in examples/
 #
 # PARAMETERS:
-# $1 is the ID of the candidate to be evaluated
-# $2 is the instance ID
+# $1 is the configuration number
+# $2 is the instance id
 # $3 is the seed
 # $4 is the instance name
-# $5 is the total number of candidates
-# The rest are the IDs of all candidates run for this instance
+# $5 is the total number of configurations alive in this iteration
+# The rest are the IDs of all configurations run for this instance
+#
+# ONLY FOR ELITIST RACE: The rest ($* after `shift 5') are the ids of the
+# configurations alive in this iteration. This list can be used to calculate
+# the hypervolume using previous execution results.
 #
 # RETURN VALUE:
 # This script should print a single numerical value
@@ -25,27 +29,19 @@ NORMALIZE="~/bin/nondominated --verbose -n $NORMALIZATION_RANGE -s '_nor'"
 UPDATELIMITS="2>&1 | grep -E 'minimum|maximum'  | sed  's/:/:\n/'"
 
 # A program for computing the hypervolume. Download hypervolume
-# code from http://iridia.ulb.ac.be/~manuel/hypervolume
+# code from http://lopez-ibanez.eu/hypervolume
 HV="~/bin/hv --quiet -r $REFERENCE_POINT"
 
-CANDIDATE="$1"
+CONFIGURATION="$1"
 INSTANCEID="$2"
 SEED="$3"
 INSTANCE="$4"
-TOTALCANDIDATES="$5"
+TOTALCONFIGURATIONS="$5"
 shift 5 || error "Not enough parameters to $0"
 ALLIDS=$*
 
-STDOUT=c${CANDIDATE}-${INSTANCEID}.stdout
-STDERR=c${CANDIDATE}-${INSTANCEID}.stderr
-
-# TODO: Use /tmp for all temporary files, i.e., put target-data under /tmp
-cd target-data || error "cannot change to directory 'target-data'"
-
-ALLFILES=
-for FILENAME in ALLIDS; do
-    ALLFILES="$ALLFILES c${FILENAME}-${INSTANCEID}.stdout"
-done
+STDOUT=c${CONFIGURATION}-${INSTANCEID}.stdout
+STDERR=c${CONFIGURATION}-${INSTANCEID}.stderr
 
 calc_measure() {
     LIMITSFILE=limits-${INSTANCEID}.txt
@@ -58,12 +54,20 @@ calc_measure() {
     fi
 }
 
+# TODO: Use /tmp for all temporary files, i.e., put target-data under /tmp
+cd target-data || error "cannot change to directory 'target-data'"
+
+ALLFILES=
+for FILENAME in ALLIDS; do
+    ALLFILES="$ALLFILES c${FILENAME}-${INSTANCEID}.stdout"
+done
+
 # First normalize output files, unless they are ready.
 while ! ls ${ALLFILES}_nor &> /dev/null ; do
     # Check that all output files are there
     NUM=$(ls -1 ${ALLFILES} 2> /dev/null | wc --lines)
-    if [ "$NUM" -ne "$TOTALCANDIDATES" ]; then
-        error_sleep "only found $NUM files out of $TOTALCANDIDATES"
+    if [ "$NUM" -ne "$TOTALCONFIGURATIONS" ]; then
+        error_sleep "only found $NUM files out of $TOTALCONFIGURATIONS: ${ALLFILES}"
         continue
     fi
     # Check every STDERR
@@ -74,19 +78,17 @@ while ! ls ${ALLFILES}_nor &> /dev/null ; do
     done
     calc_measure
     rm -f error.log
-    TODELETE=$(comm -23 <(ls -1 c*-${INSTANCEID}.* | sort) <(ls -1 $ALLFILES))
     # Comment out if you wish to keep all output files around
-    echo "rm -f $TODELETE"
+    comm --output-delimiter=" " -23 <(ls -1 c*-*.* | sort) <(ls -1 ${ALLFILES//-${INSTANCEID}.stdout/-*.*} | sort) | xargs -r rm -f
+    break
 done
 
-if [ -s "${STDOUT}_nor" ]; then
-    COST=$($HV ${STDOUT}_nor || error "calculating hypervolume failed")
-    # Negative because hypervolume is maximised but irace minimises.
-    echo "-$COST"
-    exit 0
-else
+if [ ! -s "${STDOUT}_nor" ]; then
     error "${STDOUT}_nor: No such file or directory"
 fi
+COST=$(eval "$HV ${STDOUT}_nor" || error "calculating hypervolume failed")
+# Negative because hypervolume is maximised but irace minimises.
+echo "-$COST"
 
 error() {
     echo "`TZ=UTC date`: error: $@"
@@ -100,3 +102,5 @@ error_sleep() {
     echo "`TZ=UTC date`: error: $@" >> error.log
     sleep 60
 }
+
+exit 0
diff --git a/inst/examples/moaco/target-evaluator b/inst/examples/moaco/target-evaluator
--- a/inst/examples/moaco/target-evaluator
+++ b/inst/examples/moaco/target-evaluator
@@ -20,6 +20,19 @@
 # RETURN VALUE:
 # This script should print a single numerical value
 ###############################################################################
+error() {
+    echo "`TZ=UTC date`: error: $@"
+    if [ -s error.log ]; then
+        cat error.log
+    fi
+    exit 1
+}
+
+error_sleep() {
+    echo "`TZ=UTC date`: error: $@" >> error.log
+    sleep 60
+}
+
 NORMALIZATION_RANGE="'1 2'"
 REFERENCE_POINT="'2.1 2.1'"
 
@@ -43,19 +56,6 @@ ALLIDS=$*
 STDOUT=c${CONFIGURATION}-${INSTANCEID}.stdout
 STDERR=c${CONFIGURATION}-${INSTANCEID}.stderr
 
-error() {
-    echo "`TZ=UTC date`: error: $@"
-    if [ -s error.log ]; then
-        cat error.log
-    fi
-    exit 1
-}
-
-error_sleep() {
-    echo "`TZ=UTC date`: error: $@" >> error.log
-    sleep 60
-}
-
 calc_measure() {
     LIMITSFILE=limits-${INSTANCEID}.txt
     LIMITSTMP=limits-${INSTANCEID}.tmp
@@ -66,17 +66,15 @@ calc_measure() {
     else
        eval "$NORMALIZE $ALLFILES $UPDATELIMITS" > $LIMITSFILE
     fi
-
 }
 
-tmp="./target-runner-tmp"
-cd ${tmp} || error "cannot change to directory \'${tmp}\'"
+# TODO: Use /tmp for all temporary files, i.e., put target-data under /tmp
+cd target-data || error "cannot change to directory 'target-data'"
 
 ALLFILES=
-for FILENAME in $ALLIDS; do
+for FILENAME in ALLIDS; do
     ALLFILES="$ALLFILES c${FILENAME}-${INSTANCEID}.stdout"
 done
-
 
 # First normalize output files, unless they are ready.
 while ! ls ${ALLFILES}_nor &> /dev/null ; do
@@ -105,5 +103,5 @@ fi
 COST=$(eval "$HV ${STDOUT}_nor" || error "calculating hypervolume failed")
 # Negative because hypervolume is maximised but irace minimises.
 echo "-$COST"
-exit 0
 
+exit 0
